=== valeriikundas/knu/oop/Lab2_1/Lab2/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nure.ua/thao/SummaryTask3/entity" 
	xmlns:tns="http://nure.ua/thao/SummaryTask3/entity">

	<xsd:element name="Medicine">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Medication"
							 type="tns:Medication" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Medication">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string"/>
			<xsd:element name="Pharm" type="xsd:token"/>
			<xsd:element name="Group" type="xsd:string"/>
			<xsd:element name="Analogs" type="xsd:string" />
			<xsd:element name="Versions" type="tns:Versions" />
			<xsd:element name="Certificate" type="xsd:decimal" />
			<xsd:element name="Package" type="xsd:string" />
			<xsd:element name="Dosage" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="Versions" final="restriction">
		<xsd:restriction base="xsd:string">
    			<xsd:enumeration value="Ампулы"/>
				<xsd:enumeration value="Таблетки"/>
  		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== valeriikundas/knu/oop/Lab2_1/Lab2/src/input.xml
<?xml version="1.0" encoding="UTF-8"?>

<Lab1:Medicine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:Lab1="http://nure.ua/thao/SummaryTask3/entity"
		xsi:schemaLocation="http://nure.ua/thao/SummaryTask3/entity input.xsd">		
		
	<Medication>
		<Name>Enam</Name>
		<Pharm>Dr.Reddy's</Pharm>
		<Group>Lowers blood pressure</Group>
		<Analogs>Enalapril</Analogs>
		<Versions>Pills</Versions>
		<Certificate>331233</Certificate>
		<Package>Pack of 10 pills</Package>
		<Dosage>1 pill per day</Dosage>
	</Medication>
	
	<Medication>
		<Name>Mezim</Name>
		<Pharm>Berlin-chemie</Pharm>
		<Group>Enzyme preparations</Group>
		<Analogs>Creon, Pancreatin, Panzinorm</Analogs>
		<Versions>Pills</Versions>
		<Certificate>0293410</Certificate>
		<Package>Pack of 10 tables</Package>
		<Dosage>2-3 pills per day during food </Dosage>
	</Medication>

	<Medication>
		<Name>Noshpa</Name>
		<Pharm>Sanofi</Pharm>
		<Group>Antispasmodic</Group>
		<Analogs>Drotaverin</Analogs>
		<Versions>Ampoules</Versions>
		<Certificate>2937983</Certificate>
		<Package>Pack of 24</Package>
		<Dosage>40 mg/pill</Dosage>
	</Medication>	

</Lab1:Medicine>
